# Generated by Django 3.0.2 on 2020-01-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='rolfk',
        ),
        migrations.AddField(
            model_name='persona',
            name='rol',
            field=models.CharField(default='usuario', help_text='Aqui van los Roles', max_length=20),
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
