# Generated by Django 3.0.2 on 2020-01-20 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0002_auto_20200119_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='regla',
            field=models.ManyToManyField(help_text='Seleccione una regla para este Lugar', null=True, to='MiApp.Regla'),
        ),
    ]
