# Generated by Django 3.0.2 on 2020-01-20 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0003_auto_20200119_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lugar',
            name='regla',
        ),
    ]
