# Generated by Django 3.0.2 on 2020-02-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0004_remove_lugar_regla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='latitud',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='longitud',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='puntuacion',
            field=models.TextField(),
        ),
    ]
